# Generated by Django 5.1.4 on 2024-12-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
