# Generated by Django 5.1.4 on 2024-12-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtoken',
            name='is_active',
        ),
    ]
