# Generated by Django 5.1.4 on 2024-12-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_bookingtoken_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtoken',
            old_name='event',
            new_name='event_queue',
        ),
    ]
