# Generated by Django 5.1.4 on 2024-12-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_event_bookingtoken_event_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtoken',
            name='event_queue',
        ),
        migrations.AddField(
            model_name='bookingtoken',
            name='event',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tokens', to='event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='active_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EventQueue',
        ),
    ]
